version: '3'

networks:
  pergunovdv-netology-prometheus:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
        gateway: 10.5.0.1

volumes:
    prometheus_data:
    grafana-data:

services:

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: pergunovdv-netology-prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    restart: always
    ports:
      - 9090:9090
    networks:
      - pergunovdv-netology-prometheus

  pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: pergunovdv-netology-pushgateway
    ports:
      - 9091:9091
    networks:
      - pergunovdv-netology-prometheus
    depends_on:
      - prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: pergunovdv-netology-grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/custom.ini
    ports:
      - 80:3000
    volumes:
      - ./grafana:/etc/grafana
      - grafana-data:/var/lib/grafana
    networks:
      - pergunovdv-netology-prometheus
    depends_on:
      - prometheus
    restart: unless-stopped




